global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']


  - job_name: 'healthcheck-url'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
        #replacement: localhost:9115  # The blackbox exporter's real hostname:port.


  - job_name: 'healthcheck-url-ip4'
    metrics_path: /probe
    params:
      module: [http_2xx_with_ip4]
      #module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
        #replacement: localhost:9115  # The blackbox exporter's real hostname:port.


  - job_name: 'stripe-healthcheck'
    metrics_path: /probe
    params:
      module: [http_2xx_for_stripe_api]
    static_configs:
      - targets:
        - https://api.stripe.com/v1/charges
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
        #replacement: localhost:9115  # The blackbox exporter's real hostname:port.


  - job_name: 'stripe-healthcheck-wrong-config'
    metrics_path: /probe
    params:
      module: [http_2xx_with_ip4]
      #module: [http_2xx_for_stripe_api]
    basic_auth:
      username: 'sk_test_4eC39HqLyjWDarjtT1zdp7dc'
    static_configs:
      - targets:
        - https://api.stripe.com/v1/charges
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
        #replacement: localhost:9115  # The blackbox exporter's real hostname:port.
